-- Customer profiles: residential/commercial, retainer clients, extra contacts.
ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS customer_type text NOT NULL DEFAULT 'residential',
  ADD COLUMN IF NOT EXISTS contact_person text,
  ADD COLUMN IF NOT EXISTS mobile text,
  ADD COLUMN IF NOT EXISTS preferred_contact text,
  ADD COLUMN IF NOT EXISTS tags text,
  ADD COLUMN IF NOT EXISTS is_retainer boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS retainer_plan text,
  ADD COLUMN IF NOT EXISTS retainer_monthly_fee double precision,
  ADD COLUMN IF NOT EXISTS retainer_renewal_date date;

-- Repair workflow: priority, promised date, technician, payment and warranty.
ALTER TABLE repairs
  ADD COLUMN IF NOT EXISTS priority text NOT NULL DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS due_date date,
  ADD COLUMN IF NOT EXISTS technician text,
  ADD COLUMN IF NOT EXISTS deposit double precision,
  ADD COLUMN IF NOT EXISTS paid boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS warranty_days integer;

-- Parts that a repair needs, with where to order them.
CREATE TABLE IF NOT EXISTS repair_parts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repair_id bigint NOT NULL REFERENCES repairs(id) ON DELETE CASCADE,
  name text NOT NULL,
  part_number text,
  supplier text,
  url text,
  quantity integer NOT NULL DEFAULT 1,
  unit_cost double precision,
  status text NOT NULL DEFAULT 'needed',
  notes text,
  ordered_at timestamptz,
  received_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS repair_parts_repair_id_idx ON repair_parts(repair_id);
CREATE INDEX IF NOT EXISTS repair_parts_status_idx ON repair_parts(status);
