-- People who sign in. The "admin" account's password comes from DBREPAIRS_PASSWORD.
CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL,
  display_name text NOT NULL,
  password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'tech',
  active boolean NOT NULL DEFAULT true,
  -- Raised when a password changes or an account is disabled, which ends its sessions.
  session_version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS users_username_idx ON users (lower(username));

-- One shared team channel.
CREATE TABLE IF NOT EXISTS chat_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  author_name text NOT NULL,
  body text NOT NULL DEFAULT '',
  tags text[] NOT NULL DEFAULT '{}',
  resolved boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Files are uploaded first (message_id empty), then attached when the message is sent.
CREATE TABLE IF NOT EXISTS chat_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id bigint REFERENCES chat_messages(id) ON DELETE CASCADE,
  uploaded_by bigint REFERENCES users(id) ON DELETE SET NULL,
  filename text NOT NULL,
  content_type text NOT NULL,
  size integer NOT NULL,
  data bytea NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS chat_attachments_message_id_idx ON chat_attachments(message_id);
