-- Who changed what. Written by the API for every create, update and delete.
CREATE TABLE IF NOT EXISTS audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at timestamptz NOT NULL DEFAULT now(),
  user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  user_name text,
  action text NOT NULL,
  entity text NOT NULL,
  entity_id bigint,
  -- Kept as plain numbers (no foreign keys) so history survives deletes.
  repair_id bigint,
  customer_id bigint,
  summary text,
  changes jsonb
);
CREATE INDEX IF NOT EXISTS audit_log_at_idx ON audit_log(at DESC);
CREATE INDEX IF NOT EXISTS audit_log_repair_idx ON audit_log(repair_id);
CREATE INDEX IF NOT EXISTS audit_log_customer_idx ON audit_log(customer_id);
CREATE INDEX IF NOT EXISTS audit_log_entity_idx ON audit_log(entity, entity_id);

-- Numbers for invoices and estimates, one sequence per kind and year.
CREATE TABLE IF NOT EXISTS document_counters (
  kind text NOT NULL,
  year integer NOT NULL,
  value integer NOT NULL DEFAULT 0,
  PRIMARY KEY (kind, year)
);

-- Estimates and invoices share one table; kind tells them apart.
CREATE TABLE IF NOT EXISTS invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL CHECK (kind IN ('estimate', 'invoice')),
  number text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'draft',
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  repair_id bigint REFERENCES repairs(id) ON DELETE SET NULL,
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date,
  notes text,
  terms text,
  tax_rate numeric(6,3) NOT NULL DEFAULT 0,
  discount numeric(12,2) NOT NULL DEFAULT 0,
  subtotal numeric(12,2) NOT NULL DEFAULT 0,
  tax_amount numeric(12,2) NOT NULL DEFAULT 0,
  total numeric(12,2) NOT NULL DEFAULT 0,
  sent_at timestamptz,
  approved_at timestamptz,
  approved_name text,
  declined_at timestamptz,
  converted_to bigint REFERENCES invoices(id) ON DELETE SET NULL,
  created_by bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS invoices_customer_idx ON invoices(customer_id);
CREATE INDEX IF NOT EXISTS invoices_repair_idx ON invoices(repair_id);
CREATE INDEX IF NOT EXISTS invoices_kind_status_idx ON invoices(kind, status);

CREATE TABLE IF NOT EXISTS invoice_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  position integer NOT NULL DEFAULT 0,
  kind text NOT NULL DEFAULT 'other',
  description text NOT NULL,
  quantity numeric(12,3) NOT NULL DEFAULT 1,
  unit_price numeric(12,2) NOT NULL DEFAULT 0,
  taxable boolean NOT NULL DEFAULT true,
  amount numeric(12,2) NOT NULL DEFAULT 0,
  repair_part_id bigint REFERENCES repair_parts(id) ON DELETE SET NULL,
  time_entry_ids bigint[] NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS invoice_lines_invoice_idx ON invoice_lines(invoice_id);

CREATE TABLE IF NOT EXISTS payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  amount numeric(12,2) NOT NULL CHECK (amount > 0),
  method text NOT NULL DEFAULT 'other',
  paid_at date NOT NULL DEFAULT CURRENT_DATE,
  reference text,
  note text,
  created_by bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS payments_invoice_idx ON payments(invoice_id);
CREATE INDEX IF NOT EXISTS payments_paid_at_idx ON payments(paid_at);

-- Hours worked, on a repair or directly for a customer (on-site, remote).
CREATE TABLE IF NOT EXISTS time_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  repair_id bigint REFERENCES repairs(id) ON DELETE SET NULL,
  user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  technician text,
  work_date date NOT NULL DEFAULT CURRENT_DATE,
  minutes integer NOT NULL CHECK (minutes > 0 AND minutes <= 1440),
  description text,
  billable boolean NOT NULL DEFAULT true,
  hourly_rate numeric(12,2),
  invoice_id bigint REFERENCES invoices(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS time_entries_customer_idx ON time_entries(customer_id, work_date);
CREATE INDEX IF NOT EXISTS time_entries_repair_idx ON time_entries(repair_id);
CREATE INDEX IF NOT EXISTS time_entries_invoice_idx ON time_entries(invoice_id);

-- One running timer per person.
CREATE TABLE IF NOT EXISTS running_timers (
  user_id bigint PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  repair_id bigint REFERENCES repairs(id) ON DELETE CASCADE,
  description text,
  started_at timestamptz NOT NULL DEFAULT now()
);

-- Signatures drawn on screen: estimate approvals now, intake and pickup later.
CREATE TABLE IF NOT EXISTS signatures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL,
  invoice_id bigint REFERENCES invoices(id) ON DELETE CASCADE,
  -- Intake and pickup signatures are removed with their repair by the API.
  repair_id bigint REFERENCES repairs(id) ON DELETE SET NULL,
  signer_name text NOT NULL,
  image text NOT NULL,
  signed_at timestamptz NOT NULL DEFAULT now(),
  created_by bigint REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS signatures_invoice_idx ON signatures(invoice_id);
CREATE INDEX IF NOT EXISTS signatures_repair_idx ON signatures(repair_id);
