-- Retainer / managed-service contracts. A customer can have several (for
-- example "Server care" and "Workstations").
CREATE TABLE IF NOT EXISTS contracts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  name text NOT NULL,
  monthly_fee numeric(12,2) NOT NULL DEFAULT 0,
  hours_included numeric(8,2) NOT NULL DEFAULT 0,
  -- Price per hour above the included hours; empty uses the shop rate.
  overage_rate numeric(12,2),
  -- Promised first response, in hours, for this customer's new repairs.
  response_hours integer,
  start_date date NOT NULL DEFAULT CURRENT_DATE,
  renewal_date date,
  billing_day integer NOT NULL DEFAULT 1 CHECK (billing_day BETWEEN 1 AND 28),
  auto_invoice boolean NOT NULL DEFAULT false,
  active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS contracts_customer_idx ON contracts(customer_id);

-- Contract invoices are one per contract and month (period "YYYY-MM").
ALTER TABLE invoices
  ADD COLUMN IF NOT EXISTS contract_id bigint REFERENCES contracts(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS period text;
CREATE UNIQUE INDEX IF NOT EXISTS invoices_contract_period_idx ON invoices(contract_id, period)
  WHERE contract_id IS NOT NULL AND kind = 'invoice' AND status <> 'void';

-- Response-time targets (SLA) for contract customers.
ALTER TABLE repairs
  ADD COLUMN IF NOT EXISTS sla_due_at timestamptz,
  ADD COLUMN IF NOT EXISTS first_response_at timestamptz;

-- Recurring maintenance: a repair ticket is created before each due date.
CREATE TABLE IF NOT EXISTS maintenance_plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  contract_id bigint REFERENCES contracts(id) ON DELETE SET NULL,
  title text NOT NULL,
  description text,
  checklist text,
  frequency text NOT NULL DEFAULT 'monthly' CHECK (frequency IN ('weekly', 'monthly', 'quarterly', 'yearly')),
  interval_count integer NOT NULL DEFAULT 1 CHECK (interval_count BETWEEN 1 AND 52),
  next_due date NOT NULL,
  lead_days integer NOT NULL DEFAULT 3 CHECK (lead_days BETWEEN 0 AND 60),
  technician text,
  active boolean NOT NULL DEFAULT true,
  last_repair_id bigint REFERENCES repairs(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS maintenance_plans_due_idx ON maintenance_plans(active, next_due);

ALTER TABLE repairs ADD COLUMN IF NOT EXISTS maintenance_plan_id bigint REFERENCES maintenance_plans(id) ON DELETE SET NULL;
