-- Customers' equipment: servers, PCs, laptops, network gear.
CREATE TABLE IF NOT EXISTS assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  kind text NOT NULL DEFAULT 'other',
  name text NOT NULL,
  brand text,
  model text,
  serial_number text,
  asset_tag text,
  os text,
  cpu text,
  ram text,
  storage text,
  ip_address text,
  mac_address text,
  location text,
  purchase_date date,
  warranty_end date,
  notes text,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'retired')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS assets_customer_idx ON assets(customer_id);
CREATE INDEX IF NOT EXISTS assets_serial_idx ON assets(lower(serial_number));

ALTER TABLE repairs
  ADD COLUMN IF NOT EXISTS asset_id bigint REFERENCES assets(id) ON DELETE SET NULL,
  -- Intake: the checklist ticked at the counter and the customer's choice about their data.
  ADD COLUMN IF NOT EXISTS intake_checklist jsonb,
  ADD COLUMN IF NOT EXISTS data_backup text;
CREATE INDEX IF NOT EXISTS repairs_asset_idx ON repairs(asset_id);
ALTER TABLE maintenance_plans ADD COLUMN IF NOT EXISTS asset_id bigint REFERENCES assets(id) ON DELETE SET NULL;

-- Network notes for each customer: ISP, addresses, VLANs, Wi-Fi…
CREATE TABLE IF NOT EXISTS customer_networks (
  customer_id bigint PRIMARY KEY REFERENCES customers(id) ON DELETE CASCADE,
  isp text,
  wan_ip text,
  notes text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text
);
CREATE TABLE IF NOT EXISTS network_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  position integer NOT NULL DEFAULT 0,
  kind text NOT NULL DEFAULT 'other',
  name text NOT NULL,
  value text,
  notes text
);
CREATE INDEX IF NOT EXISTS network_items_customer_idx ON network_items(customer_id);

-- Diagrams, photos of racks and PDFs for a customer. Files live in PHOTOS_DIR like repair photos.
CREATE TABLE IF NOT EXISTS customer_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  file_name text NOT NULL UNIQUE,
  original_name text,
  content_type text NOT NULL,
  size integer NOT NULL,
  caption text,
  uploaded_by bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS customer_files_customer_idx ON customer_files(customer_id);

-- Password vault. Secrets are encrypted with VAULT_KEY (kept outside the database).
CREATE TABLE IF NOT EXISTS credentials (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  asset_id bigint REFERENCES assets(id) ON DELETE SET NULL,
  label text NOT NULL,
  username text,
  secret text,
  url text,
  notes text,
  created_by bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS credentials_customer_idx ON credentials(customer_id);

-- Drive wipe / destruction records, printed as certificates.
CREATE TABLE IF NOT EXISTS data_wipes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  certificate_number text NOT NULL UNIQUE,
  customer_id bigint NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
  repair_id bigint REFERENCES repairs(id) ON DELETE SET NULL,
  asset_id bigint REFERENCES assets(id) ON DELETE SET NULL,
  drive_model text,
  drive_serial text NOT NULL,
  capacity text,
  interface text,
  method text NOT NULL,
  tool text,
  passes integer,
  completed_at timestamptz NOT NULL DEFAULT now(),
  result text NOT NULL DEFAULT 'passed' CHECK (result IN ('passed', 'failed')),
  verified boolean NOT NULL DEFAULT false,
  technician text,
  notes text,
  created_by bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS data_wipes_customer_idx ON data_wipes(customer_id);
CREATE INDEX IF NOT EXISTS data_wipes_repair_idx ON data_wipes(repair_id);
