-- Parts kept on the shelf.
CREATE TABLE IF NOT EXISTS stock_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku text,
  name text NOT NULL,
  category text,
  brand text,
  part_number text,
  barcode text,
  supplier text,
  url text,
  cost numeric(12,2),
  price numeric(12,2),
  quantity integer NOT NULL DEFAULT 0,
  reorder_level integer NOT NULL DEFAULT 0,
  reorder_quantity integer,
  location text,
  notes text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS stock_items_sku_idx ON stock_items(lower(sku)) WHERE sku IS NOT NULL;
CREATE INDEX IF NOT EXISTS stock_items_barcode_idx ON stock_items(barcode);

-- Every change to a stock quantity, so counts can be explained.
CREATE TABLE IF NOT EXISTS stock_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id bigint NOT NULL REFERENCES stock_items(id) ON DELETE CASCADE,
  change integer NOT NULL,
  reason text NOT NULL,
  repair_id bigint REFERENCES repairs(id) ON DELETE SET NULL,
  user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  note text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS stock_movements_item_idx ON stock_movements(item_id, id DESC);

ALTER TABLE repair_parts ADD COLUMN IF NOT EXISTS stock_item_id bigint REFERENCES stock_items(id) ON DELETE SET NULL;

-- Parts sent back to a supplier (faulty, wrong, warranty).
CREATE TABLE IF NOT EXISTS supplier_returns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier text NOT NULL,
  supplier_rma text,
  item text NOT NULL,
  part_number text,
  serial_number text,
  quantity integer NOT NULL DEFAULT 1,
  reason text,
  status text NOT NULL DEFAULT 'to_ship',
  repair_id bigint REFERENCES repairs(id) ON DELETE SET NULL,
  repair_part_id bigint REFERENCES repair_parts(id) ON DELETE SET NULL,
  stock_item_id bigint REFERENCES stock_items(id) ON DELETE SET NULL,
  shipped_at date,
  tracking text,
  resolved_at date,
  credit_amount numeric(12,2),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS supplier_returns_status_idx ON supplier_returns(status);

-- Warranty comebacks point at the repair they come back from.
ALTER TABLE repairs
  ADD COLUMN IF NOT EXISTS parent_repair_id bigint REFERENCES repairs(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS is_warranty boolean NOT NULL DEFAULT false,
  -- Last time the customer was reminded to collect a finished repair.
  ADD COLUMN IF NOT EXISTS pickup_reminded_at timestamptz;
CREATE INDEX IF NOT EXISTS repairs_parent_idx ON repairs(parent_repair_id);

-- On-site visits, drop-offs, pickups and remote sessions.
CREATE TABLE IF NOT EXISTS appointments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  kind text NOT NULL DEFAULT 'onsite',
  customer_id bigint REFERENCES customers(id) ON DELETE CASCADE,
  repair_id bigint REFERENCES repairs(id) ON DELETE SET NULL,
  asset_id bigint REFERENCES assets(id) ON DELETE SET NULL,
  user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  all_day boolean NOT NULL DEFAULT false,
  address text,
  travel_minutes integer,
  notes text,
  status text NOT NULL DEFAULT 'scheduled',
  created_by bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (ends_at >= starts_at)
);
CREATE INDEX IF NOT EXISTS appointments_time_idx ON appointments(starts_at);

-- Private link for subscribing to your appointments from a phone calendar.
ALTER TABLE users ADD COLUMN IF NOT EXISTS calendar_token text UNIQUE;
