-- Every email or text the app sends, with the result.
CREATE TABLE IF NOT EXISTS outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel text NOT NULL CHECK (channel IN ('email', 'sms')),
  recipient text NOT NULL,
  subject text,
  body text NOT NULL,
  status text NOT NULL DEFAULT 'sent',
  error text,
  repair_id bigint REFERENCES repairs(id) ON DELETE SET NULL,
  customer_id bigint REFERENCES customers(id) ON DELETE SET NULL,
  invoice_id bigint REFERENCES invoices(id) ON DELETE SET NULL,
  sent_by bigint REFERENCES users(id) ON DELETE SET NULL,
  automatic boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS outbox_repair_idx ON outbox(repair_id);
CREATE INDEX IF NOT EXISTS outbox_customer_idx ON outbox(customer_id);

-- Phones and browsers that asked for notifications.
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz
);

-- Customer status page: a random token per repair, shared only with that customer.
ALTER TABLE repairs ADD COLUMN IF NOT EXISTS status_token text UNIQUE;
-- Avoid sending the same response-time warning twice.
ALTER TABLE repairs ADD COLUMN IF NOT EXISTS sla_warned_at timestamptz;

-- Knowledge base and repair checklists.
CREATE TABLE IF NOT EXISTS kb_articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  tags text,
  device_type text,
  created_by bigint REFERENCES users(id) ON DELETE SET NULL,
  updated_by bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS checklist_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  device_type text,
  items text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS repair_checklists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repair_id bigint NOT NULL REFERENCES repairs(id) ON DELETE CASCADE,
  name text NOT NULL,
  -- [{ "label": "...", "done": true, "by": "Sam", "at": "2026-10-07T10:00:00Z", "note": "..." }]
  items jsonb NOT NULL DEFAULT '[]',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS repair_checklists_repair_idx ON repair_checklists(repair_id);
